In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('NPPE1_Preprocessing1.csv')
df.shape

(4000, 14)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   CRIM          4000 non-null   float64
 1   ZN            4000 non-null   float64
 2   INDUS         4000 non-null   float64
 3   POLINDEX      4000 non-null   float64
 4   RM            4000 non-null   float64
 5   AGE           4000 non-null   float64
 6   DIS           4000 non-null   float64
 7   HIGHWAYCOUNT  4000 non-null   int64  
 8   TAX           4000 non-null   float64
 9   PTRATIO       4000 non-null   float64
 10  IMM           4000 non-null   float64
 11  BPL           4000 non-null   float64
 12  PRICE         4000 non-null   float64
 13  RIVERSIDE     4000 non-null   object 
dtypes: float64(12), int64(1), object(1)
memory usage: 437.6+ KB


In [4]:
df['PRICE'].mean()

24.355923220694248

In [5]:
len(df[df['RM'] >= 5])

3953

In [6]:
df.sort_values(by='PRICE', ascending=False).head(10)['PRICE'].mean()

52.36590175716407

In [7]:
df['RM'].unique()

array([ 6.,  7.,  8.,  9., 10., -1.,  5.,  4., 11.])

In [8]:
len(df[df['RM'] == -1])

40

In [9]:
df['AGE'].unique()

array([ 42.,  63.,  -2.,   9.,  20.,  95.,  35.,  97.,  36.,  78.,  99.,
        96.,  19.,  73.,  86.,  37.,  76.,  50.,  32.,  92., 101.,   8.,
        94.,  84.,  47.,  43.,  65.,  46.,  59.,  74.,  93.,  80.,  98.,
       102.,  56., 100.,  89.,  53.,  18.,  71.,  62.,  83.,  66.,   7.,
        77.,  91.,  90.,  58.,  57.,  60.,  87.,  75.,  34.,  85.,  48.,
        33.,  38.,  30.,  23.,  55.,  11.,  14.,  45.,  41.,  88.,  16.,
        12.,  79.,  67.,  39.,  49.,  61.,  70.,  54.,  10.,  22.,  72.,
        15.,  51.,  81.,  31.,  52.,  44.,  28.,  17.,  40.,  29.,  69.,
        64.,  24.,  82.,  26.,  68.,  27.,  13., 103.,  21.,  25.,   6.,
         5.,   3.,   4.])

In [10]:
len(df[df['AGE'] < 0])

50

In [11]:
df['RIVERSIDE'].unique()

array(['NO', 'UNKNOWN', 'YES'], dtype=object)

In [12]:
len(df[df['RIVERSIDE'] == 'UNKNOWN'])

88

In [13]:
len(df[(df['RIVERSIDE'] == 'YES') & (df['AGE'] <= 50) & (df['AGE'] > 0)])

44

In [14]:
len(df[df['HIGHWAYCOUNT'].isin([6,7,8])])

1211

In [15]:
df['CATEGORY'] = df['PRICE']
def cat_mapper(price):
    if price < 10:
        return 1
    elif 10 <= price < 20:
        return 2
    elif 20 <= price < 30:
        return 3
    elif 30 <= price < 40:
        return 4
    elif price >= 40:
        return 5

df['CATEGORY'] =  df['CATEGORY'].map(cat_mapper)

In [16]:
df.head()

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE  CATEGORY  
0        NO         3  
1        NO         3  
2        NO         2  
3        NO         3  
4        NO         3

In [17]:
df['CATEGORY'].unique()

array([3, 2, 5, 4, 1], dtype=int64)

In [18]:
df['CATEGORY'].value_counts()

CATEGORY
3    2028
2    1158
4     503
5     268
1      43
Name: count, dtype: int64

### Preprocessing

In [19]:
# room count, riverside and age with np.nan
print(df['RM'].unique())
df['RM'].replace(-1, np.nan, inplace=True)
print(df['RM'].unique())

[ 6.  7.  8.  9. 10. -1.  5.  4. 11.]
[ 6.  7.  8.  9. 10. nan  5.  4. 11.]


C:\Users\91820\AppData\Local\Temp\ipykernel_7812\3685077601.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RM'].replace(-1, np.nan, inplace=True)


In [20]:
print(df['RIVERSIDE'].unique())
df['RIVERSIDE'].replace('UNKNOWN', np.nan, inplace=True)
print(df['RIVERSIDE'].unique())

['NO' 'UNKNOWN' 'YES']
['NO' nan 'YES']


C:\Users\91820\AppData\Local\Temp\ipykernel_7812\2468581205.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RIVERSIDE'].replace('UNKNOWN', np.nan, inplace=True)


In [21]:
print(df['AGE'].unique())
df['AGE'].replace(-2, np.nan, inplace=True)
print(df['AGE'].unique())

[ 42.  63.  -2.   9.  20.  95.  35.  97.  36.  78.  99.  96.  19.  73.
  86.  37.  76.  50.  32.  92. 101.   8.  94.  84.  47.  43.  65.  46.
  59.  74.  93.  80.  98. 102.  56. 100.  89.  53.  18.  71.  62.  83.
  66.   7.  77.  91.  90.  58.  57.  60.  87.  75.  34.  85.  48.  33.
  38.  30.  23.  55.  11.  14.  45.  41.  88.  16.  12.  79.  67.  39.
  49.  61.  70.  54.  10.  22.  72.  15.  51.  81.  31.  52.  44.  28.
  17.  40.  29.  69.  64.  24.  82.  26.  68.  27.  13. 103.  21.  25.
   6.   5.   3.   4.]
[ 42.  63.  nan   9.  20.  95.  35.  97.  36.  78.  99.  96.  19.  73.
  86.  37.  76.  50.  32.  92. 101.   8.  94.  84.  47.  43.  65.  46.
  59.  74.  93.  80.  98. 102.  56. 100.  89.  53.  18.  71.  62.  83.
  66.   7.  77.  91.  90.  58.  57.  60.  87.  75.  34.  85.  48.  33.
  38.  30.  23.  55.  11.  14.  45.  41.  88.  16.  12.  79.  67.  39.
  49.  61.  70.  54.  10.  22.  72.  15.  51.  81.  31.  52.  44.  28.
  17.  40.  29.  69.  64.  24.  82.  26.  68.  27.  13.

C:\Users\91820\AppData\Local\Temp\ipykernel_7812\3330371073.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['AGE'].replace(-2, np.nan, inplace=True)


In [22]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['PRICE'])
y = df['PRICE']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [23]:
X_train.shape

(2800, 14)

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

# Step 1: Drop CATEGORY column

# Steps 2, 3, 5-11: Min Max Scaling for specified columns
columns_scaler_min_max = ['CRIM', 'ZN', 'POLINDEX', 'DIS', 'HIGHWAYCOUNT', 'TAX', 'PTRATIO', 'IMM', 'BPL']

# Step 4: Standard Scaling for INDUS
columns_scalar_standard = ['INDUS']

# Step 12: Impute with median then Min Max Scaling for RM
rm_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', MinMaxScaler())
])

# Step 13: Impute with mean then Min Max Scaling for AGE
age_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', MinMaxScaler())
])

# Step 14: Impute with most frequent then one hot encode for RIVERSIDE
riverside_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(sparse_output=False))
])

# Combine into a ColumnTransformer
preprocessor = ColumnTransformer([
    ('minmax',      MinMaxScaler(),     columns_scaler_min_max),
    ('std',         StandardScaler(),   columns_scalar_standard),
    ('rm',          rm_pipeline,        ['RM']),
    ('age',         age_pipeline,       ['AGE']),
    ('riverside',   riverside_pipeline, ['RIVERSIDE'])
])

preprocessor.set_output(transform='pandas')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ['CRIM', 'ZN', 'POLINDEX', 'DIS',
                                  'HIGHWAYCOUNT', 'TAX', 'PTRATIO', 'IMM',
                                  'BPL']),
                                ('std', StandardScaler(), ['INDUS']),
                                ('rm',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['RM']),
                                ('age',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', MinMaxScaler())]),
                                 ['AGE']),
                                ('riverside',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(sparse_output=False))]),
                                 ['RIVERSIDE'])])

In [25]:
preprocessor.fit_transform(X_train)

minmax__CRIM  minmax__ZN  minmax__POLINDEX  minmax__DIS  \
3336      0.189700    0.004561          0.033842     0.124347   
2540      0.036362    0.202330          0.162887     0.271862   
332       0.531739    0.010602          0.652160     0.085051   
852       0.358052    0.009848          0.301953     0.067032   
1036      0.110154    0.017579          0.158678     0.325495   
...            ...         ...               ...          ...   
835       0.108279    0.006169          0.271625     0.137714   
3264      0.038962    0.005680          0.179231     0.490348   
1653      0.231637    0.002989          0.474648     0.281366   
2607      0.019910    0.010449          0.248182     0.139128   
2732      0.014678    0.008527          0.102795     0.138143   

      minmax__HIGHWAYCOUNT  minmax__TAX  minmax__PTRATIO  minmax__IMM  \
3336              0.192308     0.374853         0.829378     0.989745   
2540              0.115385     0.069331         0.690556     0.976549   
332               0.884615     0.912012         0.792344     0.937695   
852               0.192308     0.410736         0.214812     0.658560   
1036              0.192308     0.223330         0.658217     0.992762   
...                    ...          ...              ...          ...   
835               0.153846     0.411110         0.283893     0.860627   
3264              0.153846     0.191885         0.709585     0.995029   
1653              0.884615     0.911096         0.775340     0.982969   
2607              0.192308     0.388282         0.613336     0.992426   
2732              0.192308     0.379194         0.778631     0.983039   

      minmax__BPL  std__INDUS    rm__RM  age__AGE  riverside__RIVERSIDE_NO  \
3336     0.419050   -0.239852  0.428571  0.860000                      1.0   
2540     0.140763   -0.529958  0.571429  0.640453                      0.0   
332      0.047807    1.194743  0.142857  0.970000                      1.0   
852      0.436328    1.289528  0.285714  0.960000                      1.0   
1036     0.324922   -0.038482  0.714286  0.560000                      1.0   
...           ...         ...       ...       ...                      ...   
835      0.306643    1.333493  0.285714  0.860000                      0.0   
3264     0.149164   -0.474956  0.428571  0.380000                      1.0   
1653     0.266071    1.114639  0.285714  0.390000                      1.0   
2607     0.361401   -0.105376  0.571429  0.400000                      1.0   
2732     0.310408   -0.141620  0.571429  0.880000                      1.0   

      riverside__RIVERSIDE_YES  
3336                       0.0  
2540                       1.0  
332                        0.0  
852                        0.0  
1036                       0.0  
...                        ...  
835                        1.0  
3264                       0.0  
1653                       0.0  
2607                       0.0  
2732                       0.0  

[2800 rows x 14 columns]

In [26]:
preprocessor.transform(X_test).mean().mean()

0.38617456550975626